### ISSUE TITLE
Create a MANY server mock crate

### ISSUE THREAD

**Issue by hansl** [liftedinit/many-rs#164]
This can even be part of the `many` cli tool. To facilitate with development against MANY modules that don't exist yet.

**Comment by fmorency** [comment]
As a user, I want to be able to start a server that will send pre-configured responses to requests.

Response configuration should be located in a configuration file.

This will be used to develop and facilitate module development and integration.


E.g.:
```json5
{
 "endpoint": "ledger.send",  // The endpoint
 "response": "....",         // The response to send back
}
```

Some of the responses will probably require some value from the request itself, like identities, etc. Hardcode as much as you can, but you could maybe implement some DSL/Tagging.

Please make a plan before implementing anything so we can review and iterate on it.
