### ISSUE TITLE
Fix graph script and rewrite graph in README

### ISSUE THREAD

**Issue by hansl** [liftedinit/many-rs#188]
- This graph is very difficult to read. 
  - Is it possible to create groups in mermaid?
- There is at least one inaccuracy: `many-server --> many-client;`, which is wrong. I would suggest reviewing the whole thing.
- We should document that this graph reads "Crate -is a dependency of-> Crate". Intuitively, I was expecting the other way around, i.e., "Crate -depends on-> Crate".

_Originally posted by @fmorency in https://github.com/liftedinit/many-rs/pull/184#discussion_r956035062_

**Comment by fmorency** [comment]
Closing as the graph was removed during the mono repo merge.
