### ISSUE TITLE
Refactor Memo to follow the specification

### ISSUE THREAD

**Issue by fmorency** [liftedinit/many-rs#199]
`Memo` should be

```
memo = [ + (tstr / (bstr .cbor any)) ]
```

See specification in [1]

[1]: https://github.com/many-protocol/specification/blob/f1a2bad7ee9413d4ec6c068660e2366e05c342e6/spec/cddl/types.cddl#L41-L47

**Comment by hansl** [comment]
Note: I have a PR in flight for this.

**Comment by hansl** [comment]
Tracking this in https://github.com/liftedinit/roadmap/issues/7
