### ISSUE TITLE
Migrate Docker Nix to Bazel

### ISSUE THREAD

**Issue by fmorency** [liftedinit/many-rs#265]
Drop Nix and use Bazel to build our Docker images.

We lack internal Nix expertise to continue using it.

References
- https://github.com/bazelbuild/rules_docker
- https://github.com/bazelbuild/rules_docker#rust_image

**Comment by hansl** [comment]
TODO:

- [ ] Build binaries inside docker container, or at least using the same dependencies as the target
- [ ] Build target images from inside docker
