### ISSUE TITLE
Split CI tests by timing data

### ISSUE THREAD

**Issue by fmorency** [liftedinit/many-rs#333]
Follow-up on #330 

Split tests by timing data to distribute tests on executors more efficiently.

Running `bats` with `--formatter=junit` and `--output=` is required but is currently not directly supported by `bazel-bats`. See https://github.com/filmil/bazel-bats/issues/21

See https://circleci.com/docs/test-splitting-tutorial/#step-four-split-by-timing-data

**Comment by filmil** [comment]
Pull requests welcome. :)

**Comment by fmorency** [comment]
Fixed by #357 

I'm using my `bazel-bats` fork for the moment, but I opened https://github.com/filmil/bazel-bats/pull/22 for visibility. I need to add some tests to this PR.
